"""Test event and observation model.

This module is the seam between *collection* and *correlation*.

Collectors (CLI, debug, sniffer, Graylog) only ever record what they saw and
when they saw it, as :class:`Observation` entries. They never decide whether a
test passed. The correlation engine consumes those observations and updates
:class:`TestEvent` state.

Two rules from the specification are enforced structurally rather than by
convention:

1. Every execution of the test command is an independent test event. There is
   no global "did this message ever appear" question anywhere in the model.
2. An observation may satisfy at most one test event. ``Observation.claimed_by``
   makes matched observations consumable queue entries.

The full model is defined here in Phase 1 even though only the CLI fields are
populated yet, so that Phases 2 to 4 attach without restructuring.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Dict, Iterable, List, Optional


class Source(str, Enum):
    """Logical evidence sources."""

    CLI = "CLI"
    DEBUG = "DEBUG"
    SNIFFER = "SNIFFER"
    GRAYLOG = "GRAYLOG"
    CORRELATOR = "CORRELATOR"
    SYSTEM = "SYSTEM"


class MatchState(str, Enum):
    """Per-source outcome for one test event.

    ``UNKNOWN`` is deliberately distinct from ``MISS``: a timeout, disconnect or
    collector failure means we did not observe the evidence, which is not the
    same as establishing that it was absent.
    """

    PENDING = "PENDING"
    HIT = "HIT"
    MISS = "MISS"
    UNKNOWN = "UNKNOWN"
    NOT_ENABLED = "NOT_ENABLED"


class FinalStatus(str, Enum):
    """Classification of a completed test event."""

    PENDING = "pending"
    SUCCESS = "success"
    NOT_GENERATED = "not_generated"
    GENERATION_UNKNOWN = "generation_unknown"
    GENERATED_NOT_TRANSMITTED = "generated_not_transmitted"
    TRANSMITTED_NOT_IN_GRAYLOG = "transmitted_not_in_graylog"
    IN_GRAYLOG_WITHOUT_PACKET = "in_graylog_without_packet"
    INCONCLUSIVE = "inconclusive"

    @property
    def description(self) -> str:
        return _STATUS_DESCRIPTIONS[self]


_STATUS_DESCRIPTIONS: Dict["FinalStatus", str] = {
    FinalStatus.PENDING: "TEST STILL IN FLIGHT",
    FinalStatus.SUCCESS: "SUCCESS",
    FinalStatus.NOT_GENERATED: "FORTIMANAGER DID NOT REPORT GENERATING THE EVENT",
    FinalStatus.GENERATION_UNKNOWN: "CLI RESULT UNKNOWN (NO USABLE RESPONSE FROM FORTIMANAGER)",
    FinalStatus.GENERATED_NOT_TRANSMITTED: (
        "EVENT GENERATED BY FORTIMANAGER BUT NO MATCHING OUTBOUND PACKET OBSERVED"
    ),
    FinalStatus.TRANSMITTED_NOT_IN_GRAYLOG: (
        "EVENT TRANSMITTED BY FORTIMANAGER BUT NOT OBSERVED IN GRAYLOG"
    ),
    FinalStatus.IN_GRAYLOG_WITHOUT_PACKET: (
        "EVENT OBSERVED IN GRAYLOG WITH NO MATCHING SNIFFER RECORD"
    ),
    FinalStatus.INCONCLUSIVE: "INCONCLUSIVE",
}


@dataclass
class Observation:
    """One piece of evidence recorded by a collector.

    ``fields`` carries whatever secondary correlation keys the collector could
    extract (source/destination IP and port, device id, log_id, sequence
    number, facility, ...). The Phase 4 correlator may use them; Phase 1
    populates only what the CLI provides.
    """

    source: Source
    observed_at: datetime
    raw: str
    fields: Dict[str, Any] = field(default_factory=dict)
    claimed_by: Optional[str] = None
    sequence: int = 0

    @property
    def claimed(self) -> bool:
        return self.claimed_by is not None

    def claim(self, event_id: str) -> None:
        self.claimed_by = event_id

    def to_dict(self) -> Dict[str, Any]:
        return {
            "source": self.source.value,
            "observed_at": self.observed_at.isoformat(timespec="milliseconds"),
            "claimed_by": self.claimed_by,
            "fields": dict(self.fields),
            "raw": self.raw,
        }


@dataclass
class TestEvent:
    """State for a single execution of the test command."""

    event_id: str
    cli_start_timestamp: datetime
    cli_response_timestamp: Optional[datetime] = None
    cli_state: MatchState = MatchState.PENDING
    cli_command: str = ""
    cli_response: str = ""
    cli_error: Optional[str] = None

    debug_state: MatchState = MatchState.NOT_ENABLED
    debug_matches: List[Observation] = field(default_factory=list)

    sniffer_state: MatchState = MatchState.PENDING
    sniffer_match: Optional[Observation] = None
    sniffer_timestamp: Optional[datetime] = None

    graylog_state: MatchState = MatchState.PENDING
    graylog_match: Optional[Observation] = None
    graylog_timestamp: Optional[datetime] = None

    final_status: FinalStatus = FinalStatus.PENDING
    closed_at: Optional[datetime] = None
    fields: Dict[str, Any] = field(default_factory=dict)
    identity: Dict[str, str] = field(default_factory=dict)
    """Secondary correlation keys learned from claimed evidence."""

    # -- derived timings ----------------------------------------------------

    @property
    def cli_generated(self) -> bool:
        return self.cli_state is MatchState.HIT

    @property
    def sniffer_seen(self) -> bool:
        return self.sniffer_state is MatchState.HIT

    @property
    def graylog_seen(self) -> bool:
        return self.graylog_state is MatchState.HIT

    def _delta_ms(self, start: Optional[datetime], end: Optional[datetime]) -> Optional[float]:
        if start is None or end is None:
            return None
        return round((end - start).total_seconds() * 1000.0, 3)

    @property
    def cli_response_ms(self) -> Optional[float]:
        return self._delta_ms(self.cli_start_timestamp, self.cli_response_timestamp)

    @property
    def cli_to_sniffer_ms(self) -> Optional[float]:
        return self._delta_ms(self.cli_start_timestamp, self.sniffer_timestamp)

    @property
    def sniffer_to_graylog_ms(self) -> Optional[float]:
        return self._delta_ms(self.sniffer_timestamp, self.graylog_timestamp)

    @property
    def cli_to_graylog_ms(self) -> Optional[float]:
        return self._delta_ms(self.cli_start_timestamp, self.graylog_timestamp)

    @property
    def is_open(self) -> bool:
        return self.final_status is FinalStatus.PENDING

    # -- classification -----------------------------------------------------

    def classify(self) -> FinalStatus:
        """Derive the final status from the per-source states.

        Called by the correlator when a test event's correlation window closes.
        The rules mirror the specification's result classification table, with
        UNKNOWN treated as "we could not tell" rather than as a failure.
        """
        cli = self.cli_state
        sniffer = self.sniffer_state
        graylog = self.graylog_state

        if cli is MatchState.MISS:
            return FinalStatus.NOT_GENERATED
        if cli in (MatchState.UNKNOWN, MatchState.PENDING):
            return FinalStatus.GENERATION_UNKNOWN

        sniffer_hit = sniffer is MatchState.HIT
        graylog_hit = graylog is MatchState.HIT
        sniffer_off = sniffer is MatchState.NOT_ENABLED
        graylog_off = graylog is MatchState.NOT_ENABLED

        # Everything that is switched on produced a hit.
        if (sniffer_hit or sniffer_off) and (graylog_hit or graylog_off):
            if sniffer_off and graylog_off:
                # CLI-only run (Phase 1): the strongest claim available is that
                # FortiManager reported generating the event.
                return FinalStatus.SUCCESS
            return FinalStatus.SUCCESS

        if graylog_hit and sniffer is MatchState.MISS:
            return FinalStatus.IN_GRAYLOG_WITHOUT_PACKET
        if sniffer_hit and graylog is MatchState.MISS:
            return FinalStatus.TRANSMITTED_NOT_IN_GRAYLOG
        if sniffer is MatchState.MISS and graylog in (MatchState.MISS, MatchState.NOT_ENABLED):
            return FinalStatus.GENERATED_NOT_TRANSMITTED
        if sniffer_off and graylog is MatchState.MISS:
            return FinalStatus.TRANSMITTED_NOT_IN_GRAYLOG
        return FinalStatus.INCONCLUSIVE

    def close(self, when: Optional[datetime] = None) -> FinalStatus:
        """Resolve any still-pending source states and classify the event."""
        if self.cli_state is MatchState.PENDING:
            self.cli_state = MatchState.UNKNOWN
        if self.sniffer_state is MatchState.PENDING:
            self.sniffer_state = MatchState.MISS
        if self.graylog_state is MatchState.PENDING:
            self.graylog_state = MatchState.MISS
        if self.debug_state is MatchState.PENDING:
            self.debug_state = MatchState.MISS
        self.final_status = self.classify()
        self.closed_at = when or datetime.now()
        return self.final_status

    # -- serialisation ------------------------------------------------------

    @staticmethod
    def _iso(moment: Optional[datetime]) -> Optional[str]:
        return moment.isoformat(timespec="milliseconds") if moment else None

    def to_dict(self, include_raw: bool = False) -> Dict[str, Any]:
        record: Dict[str, Any] = {
            "event_id": self.event_id,
            "cli_start": self._iso(self.cli_start_timestamp),
            "cli_response": self._iso(self.cli_response_timestamp),
            "cli_state": self.cli_state.value,
            "cli_generated": self.cli_generated,
            "cli_command": self.cli_command,
            "cli_error": self.cli_error,
            "debug_state": self.debug_state.value,
            "debug_match_count": len(self.debug_matches),
            "sniffer_state": self.sniffer_state.value,
            "sniffer_seen": self.sniffer_seen,
            "sniffer_timestamp": self._iso(self.sniffer_timestamp),
            "graylog_state": self.graylog_state.value,
            "graylog_seen": self.graylog_seen,
            "graylog_timestamp": self._iso(self.graylog_timestamp),
            "cli_response_ms": self.cli_response_ms,
            "cli_to_sniffer_ms": self.cli_to_sniffer_ms,
            "sniffer_to_graylog_ms": self.sniffer_to_graylog_ms,
            "cli_to_graylog_ms": self.cli_to_graylog_ms,
            "result": self.final_status.value,
            "result_description": self.final_status.description,
            "closed_at": self._iso(self.closed_at),
            "identity": " ".join(f"{k}={v}" for k, v in sorted(self.identity.items())),
        }
        if self.identity:
            record["identity"] = dict(self.identity)
        if self.fields:
            record["fields"] = dict(self.fields)
        if include_raw:
            record["cli_response_text"] = self.cli_response
            if self.sniffer_match is not None:
                record["sniffer_evidence"] = self.sniffer_match.to_dict()
            if self.graylog_match is not None:
                record["graylog_evidence"] = self.graylog_match.to_dict()
            if self.debug_matches:
                record["debug_evidence"] = [o.to_dict() for o in self.debug_matches]
        return record


class ObservationQueue:
    """Ordered, consumable store of observations from one source.

    Observations are appended in arrival order. ``claim_next`` hands out the
    oldest unclaimed observation inside a time window, which implements the
    "next eligible unclaimed match" rule from the specification.
    """

    def __init__(self, source: Source, allow_reuse: bool = False) -> None:
        self.source = source
        self.allow_reuse = allow_reuse
        self._items: List[Observation] = []
        self._counter = itertools.count(1)

    def __len__(self) -> int:
        return len(self._items)

    @property
    def items(self) -> List[Observation]:
        return list(self._items)

    @property
    def unclaimed_count(self) -> int:
        return sum(1 for item in self._items if not item.claimed)

    def add(
        self,
        observed_at: datetime,
        raw: str,
        fields: Optional[Dict[str, Any]] = None,
    ) -> Observation:
        observation = Observation(
            source=self.source,
            observed_at=observed_at,
            raw=raw,
            fields=dict(fields or {}),
            sequence=next(self._counter),
        )
        self._items.append(observation)
        return observation

    def claim_next(
        self,
        event_id: str,
        not_before: datetime,
        not_after: datetime,
        predicate: Optional[Any] = None,
    ) -> Optional[Observation]:
        """Claim the oldest unclaimed observation within ``[not_before, not_after]``.

        ``predicate`` is an optional ``Callable[[Observation], bool]`` used by
        later phases to add secondary correlation fields (source IP, log_id,
        sequence number and so on) without changing this signature.
        """
        for item in self._items:
            if item.claimed and not self.allow_reuse:
                continue
            if item.observed_at < not_before or item.observed_at > not_after:
                continue
            if predicate is not None and not predicate(item):
                continue
            if not self.allow_reuse:
                item.claim(event_id)
            return item
        return None

    def prune_before(self, cutoff: datetime) -> int:
        """Drop claimed observations older than ``cutoff`` to bound memory."""
        keep = [i for i in self._items if not i.claimed or i.observed_at >= cutoff]
        removed = len(self._items) - len(keep)
        self._items = keep
        return removed


class EventTracker:
    """Owns test events and the per-source observation queues."""

    def __init__(self, allow_reuse: bool = False, id_prefix: str = "TEST") -> None:
        self._events: List[TestEvent] = []
        self._by_id: Dict[str, TestEvent] = {}
        self._counter = itertools.count(1)
        self._id_prefix = id_prefix
        self.queues: Dict[Source, ObservationQueue] = {
            source: ObservationQueue(source, allow_reuse=allow_reuse)
            for source in (Source.CLI, Source.DEBUG, Source.SNIFFER, Source.GRAYLOG)
        }

    # -- events -------------------------------------------------------------

    def next_event_id(self) -> str:
        return f"{self._id_prefix}-{next(self._counter):06d}"

    def create_event(self, started_at: datetime, command: str = "") -> TestEvent:
        event = TestEvent(
            event_id=self.next_event_id(),
            cli_start_timestamp=started_at,
            cli_command=command,
        )
        self._events.append(event)
        self._by_id[event.event_id] = event
        return event

    def get(self, event_id: str) -> Optional[TestEvent]:
        return self._by_id.get(event_id)

    @property
    def events(self) -> List[TestEvent]:
        return list(self._events)

    @property
    def count(self) -> int:
        return len(self._events)

    def open_events(self) -> List[TestEvent]:
        return [e for e in self._events if e.is_open]

    def events_awaiting(self, older_than: datetime) -> List[TestEvent]:
        """Open events whose start time is at or before ``older_than``."""
        return [e for e in self._events if e.is_open and e.cli_start_timestamp <= older_than]

    def close_all(self, when: Optional[datetime] = None) -> List[TestEvent]:
        moment = when or datetime.now()
        closed = []
        for event in self._events:
            if event.is_open:
                event.close(moment)
                closed.append(event)
        return closed

    # -- observations -------------------------------------------------------

    def record(
        self,
        source: Source,
        observed_at: datetime,
        raw: str,
        fields: Optional[Dict[str, Any]] = None,
    ) -> Observation:
        queue = self.queues.get(source)
        if queue is None:
            raise KeyError(f"no observation queue for source {source}")
        return queue.add(observed_at, raw, fields)

    def claim(
        self,
        source: Source,
        event_id: str,
        not_before: datetime,
        window: timedelta,
        tolerance: timedelta = timedelta(0),
        predicate: Optional[Any] = None,
        not_after: Optional[datetime] = None,
    ) -> Optional[Observation]:
        """Claim the next eligible unclaimed observation for ``event_id``.

        ``not_after`` overrides the end of the window, which the correlator
        uses to stop one test event from consuming evidence that belongs to the
        next one.
        """
        queue = self.queues.get(source)
        if queue is None:
            return None
        return queue.claim_next(
            event_id,
            not_before=not_before - tolerance,
            not_after=not_after if not_after is not None else not_before + window,
            predicate=predicate,
        )

    def unclaimed(self, source: Source) -> List[Observation]:
        queue = self.queues.get(source)
        if queue is None:
            return []
        return [item for item in queue.items if not item.claimed]

    def iter_all_observations(self) -> Iterable[Observation]:
        for queue in self.queues.values():
            yield from queue.items
